language: csharp
mono: none
addons:
  chrome: stable
dotnet: 5.0.202
install:
  - dotnet restore Protractor.sln
script:
  - dotnet build examples/Protractor.Samples/Protractor.Samples.csproj
  - dotnet test examples/Protractor.Samples/Protractor.Samples.csproj
